#create a new db if starting new. name it camops_db
spring.datasource.url=jdbc:mysql://localhost:3306/camops_db?serverTimezone=UTC

# add YOUR db info here
spring.datasource.username=root
spring.datasource.password=mysql_password_eka_methanata_suddala

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true