spring.datasource.url=jdbc:sqlserver://DESKTOP-MRAQATP\\MSSQLSERVER2;databaseName=camops_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true